### ISSUE TITLE
能说说koa换成go的原因么

### ISSUE THREAD

**Issue by zkeyword** [acgzone/acgzone-server#3]

**Comment by 132yse** [comment]
唉，现在正在逐步换回 koa
当时 koa 换 go 主要是考虑：
1. 当时需要分离端口，如果用 koa 写，需要多开一个进程，而我当时对 koa 其实没什么新的实践（现在还是没有），所以准备换一个语言找找新鲜感
2. node 性能挺差的，不过百分之八十的性能损耗全都来自 ssr，以及我们服务器太差的原因

以上，但是我们因为一些原因，目前正在进行后端 API 的重构，又要切回 koa

**Comment by 132yse** [comment]
我们为了缩减维护量，决定砍掉go的部分，使用koa重写
这个 issue 先关了

**Comment by huiyifyj** [comment]
个人觉得还是 golang 的好, 后端用了，觉得还是 go 性能更好.
golang 的 web 框架推荐 [echo](https://github.com/labstack/echo) 和 [gin](https://github.com/gin-gonic/gin).
而且也有现成的 orm, 推荐 , [xorm](https://github.com/go-xorm/xorm).

**Comment by 132yse** [comment]
@huiyifyj 有点道理，不是 go 的性能好，是 node 性能太差了
我们暂时不移除 go，先凑合着吧

**Comment by huiyifyj** [comment]
go 性能确实是算好的了，除了 c/c++ 和 rust，应该没有其他语言能好过 golang 了。
不过你源码竟然是用原生net包写的，很少见啊。

**Comment by 132yse** [comment]
> 不过你源码竟然是用原生网包写的，很少见啊
不少见呀，go 的框架带来不了太大的收益，直接裸写更有利于学习

用 go 写 web 主要是因为 go 简单，其实用不到 go 的协程优势，不过即便如此，性能也会比 node 好太多，关键还是 node 性能太差

**Comment by huiyifyj** [comment]
确实原生包更利于学习，但是项目一旦大了，还是容易造成紊乱，想起我java web的项目，用的原生servlet + jsp，最后项目越写越大，写的自己都不想写了。最后还是用了 ssm 重构。
